### PR TITLE
Operation of three components

### PR DESCRIPTION
**Pull request by gongfchen**

### CODE REVIEW

**Comment by nobelletay** [comment]
Did you write or copy these code from elsewhere? What's the PR doing?

**Comment by gongfchen** [comment]
Marios and I are combining operations of CA and middle daemon together. This is the code structure we write. I will improve it later. I forked it because I did not access to the repo haha

**Comment by nobelletay** [comment]
Does the build succeed?

**Comment by gongfchen** [comment]
oh i see what you mean. yeah i can improve it until the final version is ready and we merge

**Review by nobelletay — APPROVED** [review]
Looks good to me. Needs cleanup for sure but we can do that later. Thanks for working on these core functions!

**Pull request closed without merging**
